-- Suppression des anciennes tables
DROP TABLE IF EXISTS ACCOUNTS_CUSTOMER_GROUPS;

DROP TABLE IF EXISTS ACCOUNTS_CUSTOMER_USER_PERMISSIONS;

DROP TABLE IF EXISTS AUTH_GROUP_PERMISSIONS;

DROP TABLE IF EXISTS BLOG_POST_EVENT_ARTWORKS;

DROP TABLE IF EXISTS STORE_CART_ORDERS;

DROP TABLE IF EXISTS STORE_CHECKOUT_ORDERS;

DROP TABLE IF EXISTS STORE_PAYMENT;

DROP TABLE IF EXISTS DJANGO_ADMIN_LOG;

DROP TABLE IF EXISTS STORE_ORDER;

DROP TABLE IF EXISTS STORE_CART;

DROP TABLE IF EXISTS STORE_CHECKOUT;

DROP TABLE IF EXISTS STORE_ARTWORK;

DROP TABLE IF EXISTS BLOG_POST;

DROP TABLE IF EXISTS AUTH_GROUP;

DROP TABLE IF EXISTS AUTH_PERMISSION;

DROP TABLE IF EXISTS STORE_MEDIUM;

DROP TABLE IF EXISTS STORE_CATEGORY;

DROP TABLE IF EXISTS ACCOUNTS_CUSTOMER;

DROP TABLE IF EXISTS DJANGO_CONTENT_TYPE;

DROP TABLE IF EXISTS DJANGO_MIGRATIONS;

DROP TABLE IF EXISTS DJANGO_SESSION;

-- Tables de base sans dépendances
CREATE TABLE DJANGO_CONTENT_TYPE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APP_LABEL VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL
);

CREATE TABLE AUTH_PERMISSION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTENT_TYPE_ID INT NOT NULL,
    CODENAME VARCHAR(100) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (CONTENT_TYPE_ID) REFERENCES DJANGO_CONTENT_TYPE(ID)
);

CREATE TABLE AUTH_GROUP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE STORE_CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL UNIQUE,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

CREATE TABLE STORE_MEDIUM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

CREATE TABLE ACCOUNTS_CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PASSWORD VARCHAR(128) NOT NULL,
    LAST_LOGIN DATETIME NULL,
    IS_SUPERUSER BOOLEAN NOT NULL,
    USERNAME VARCHAR(150) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(150) NOT NULL,
    LAST_NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(254) NOT NULL,
    IS_STAFF BOOLEAN NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    DATE_JOINED DATETIME NOT NULL
);

-- Tables avec dépendances
CREATE TABLE AUTH_GROUP_PERMISSIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES AUTH_GROUP(ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES AUTH_PERMISSION(ID)
);

CREATE TABLE ACCOUNTS_CUSTOMER_GROUPS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    GROUP_ID INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES AUTH_GROUP(ID)
);

CREATE TABLE ACCOUNTS_CUSTOMER_USER_PERMISSIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES AUTH_PERMISSION(ID)
);

CREATE TABLE STORE_ARTWORK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(180) NOT NULL UNIQUE,
    SLUG VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL,
    WIDTH INT UNSIGNED NOT NULL CHECK (WIDTH >= 0),
    HEIGHT INT UNSIGNED NOT NULL CHECK (HEIGHT >= 0),
    THUMBNAIL VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    CATEGORY_ID INT NOT NULL,
    MEDIUM_ID INT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES STORE_CATEGORY(ID),
    FOREIGN KEY (MEDIUM_ID) REFERENCES STORE_MEDIUM(ID)
);

CREATE TABLE BLOG_POST (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(180) NOT NULL UNIQUE,
    SLUG VARCHAR(250) NOT NULL UNIQUE,
    DESCRIPTION TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_PLACE VARCHAR(200) NOT NULL,
    THUMBNAIL VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

CREATE TABLE STORE_CART (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL,
    CUSTOMER_ID INT NOT NULL UNIQUE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID)
);

CREATE TABLE STORE_ORDER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(30) NOT NULL UNIQUE,
    QUANTITY INT NOT NULL,
    ORDERED BOOLEAN NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    ORDERED_AT DATETIME NULL,
    ARTWORK_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    FOREIGN KEY (ARTWORK_ID) REFERENCES STORE_ARTWORK(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID)
);

CREATE TABLE STORE_CART_ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CART_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES STORE_CART(ID),
    FOREIGN KEY (ORDER_ID) REFERENCES STORE_ORDER(ID)
);

CREATE TABLE STORE_CHECKOUT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(30) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID)
);

CREATE TABLE STORE_CHECKOUT_ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CHECKOUT_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY (CHECKOUT_ID) REFERENCES STORE_CHECKOUT(ID),
    FOREIGN KEY (ORDER_ID) REFERENCES STORE_ORDER(ID)
);

CREATE TABLE BLOG_POST_EVENT_ARTWORKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NOT NULL,
    ARTWORK_ID INT NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES BLOG_POST(ID),
    FOREIGN KEY (ARTWORK_ID) REFERENCES STORE_ARTWORK(ID)
);

CREATE TABLE STORE_PAYMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CURRENCY VARCHAR(10) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    CHECKOUT_ID INT NOT NULL,
    FOREIGN KEY (CHECKOUT_ID) REFERENCES STORE_CHECKOUT(ID)
);

CREATE TABLE DJANGO_ADMIN_LOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OBJECT_ID TEXT NULL,
    OBJECT_REPR VARCHAR(200) NOT NULL,
    ACTION_FLAG SMALLINT UNSIGNED NOT NULL CHECK (ACTION_FLAG >= 0),
    CHANGE_MESSAGE TEXT NOT NULL,
    CONTENT_TYPE_ID INT NULL,
    USER_ID INT NOT NULL,
    ACTION_TIME DATETIME NOT NULL,
    FOREIGN KEY (CONTENT_TYPE_ID) REFERENCES DJANGO_CONTENT_TYPE(ID),
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS_CUSTOMER(ID)
);

CREATE TABLE DJANGO_MIGRATIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APP VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    APPLIED DATETIME NOT NULL
);

CREATE TABLE DJANGO_SESSION (
    SESSION_KEY VARCHAR(40) NOT NULL PRIMARY KEY,
    SESSION_DATA TEXT NOT NULL,
    EXPIRE_DATE DATETIME NOT NULL
);

CREATE TABLE SQLITE_SEQUENCE (
    NAME VARCHAR(128) NOT NULL,
    SEQ INT NOT NULL
);