version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./art_by_mtr/.env
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ateliermrtdb"
      MYSQL_USER: "auredulvresse"
      MYSQL_PASSWORD: "Aure14902"
      MYSQL_ROOT_PASSWORD: "Aure14902"
    ports:
      - "3307:3306"

volumes:
  mysql_data: