version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 votre_projet.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ateliermrtdb"
      MYSQL_USER: "auredulvresse"
      MYSQL_PASSWORD: "Aure14902"
      MYSQL_ROOT_PASSWORD: "Aure14902"
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf
      - .:/app

volumes:
  mysql_data: