version: '3.7'

services:
  web:
    build: 
      context: .
    command: gunicorn art_by_mtr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .static:/static
    ports:
      - "8000:8000"
    env_file:
      - ./art_by_mtr/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ateliermrtdb"
      MYSQL_USER: "auredulvresse"
      MYSQL_PASSWORD: "Aure14902"
      MYSQL_ROOT_PASSWORD: "Aure14902"
    ports:
      - "3307:3306"
    
    networks:
      - app-network

networks:
  app-network:

volumes:
  static:
  mysql_data:
