# Generated by Django 5.0.6 on 2024-07-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name="Thème de l'événement")),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('event_place', models.CharField(max_length=200, verbose_name="Lieu de l'événement")),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Miniature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('event_artworks', models.ManyToManyField(blank=True, to='store.artwork', verbose_name="Œuvres de l'événement")),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'blog_post',
                'ordering': ['title'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
