# Generated by Django 5.0.6 on 2024-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name="Thème de l'évenement")),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('event_place', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_artworks', models.ManyToManyField(to='store.artwork')),
            ],
            options={
                'db_table': 'blog_post',
                'ordering': ['title'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
