# Generated by Django 5.0.6 on 2024-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_artworks',
            field=models.ManyToManyField(blank=True, to='store.artwork', verbose_name="Œuvres de l'événement"),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(verbose_name="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_place',
            field=models.CharField(max_length=200, verbose_name="Lieu de l'événement"),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=180, unique=True, verbose_name="Thème de l'événement"),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
